### ISSUE TITLE
Interface bug

### ISSUE THREAD

**Issue by ssssamstrup** [dic1911/android_URLSanitizer#11] opened 2021-12-21 06:44 UTC
Hi

I can't see the entry list or other options. Please see screenshot.

I've tried uninstalling and reinstalling the app, but get the same bug.

I'm on Android 10 on Sony XZ2 Compact.

Best, Sune
![Screenshot_20211221-073054](https://user-images.githubusercontent.com/4302516/146884125-ffa95c8a-6c32-494c-b8bb-88efdf9714bf.png)

**Comment by dic1911** [comment] 2022-01-08 05:57
I see no screenshot in this issue, maybe try upload to imgur or some other image hosting service.

**Comment by dic1911** [comment] 2022-01-08 08:54
The layout of mentioned activity/page is adjusted in latest release, please [test](https://github.com/dic1911/android_URLSanitizer/releases/tag/2.0.2) and report, or maybe close this issue if the problem is gone

**Comment by dic1911** [comment] 2022-02-28 02:44
Closing this issue as inactivity for more than a month.

**Closed as completed by dic1911** 2022-02-28 02:44 UTC

**Comment by kamzil** [comment] 2024-02-28 10:21
Having the same issue on 2.1.0. Also can't scroll in the view with all those toggles after clicking "PRIVACY REDIRECT" button. Also the text box in the bottom with different patterns is too small and unusable. Please reopen.
